"""
Remove test data before a public deploy.

WHAT COUNTS AS TEST DATA HERE, and why it is a whitelist rather than a
blocklist: the accounts to KEEP are four and knowable; the accounts to delete
are sixty-something and were generated by scripts with patterns that will
change the next time somebody writes a probe. Listing what survives means a
new kind of junk is deleted by default, and the failure mode is "an account I
meant to keep is gone" rather than "a fake shop shipped to production".

    KEEP  the admin account -- without it nobody can sign in to /admin
    KEEP  the owner's real addresses
    DROP  everything else: attack probes, smoke-test signups, escalation
          probes, rotation/cookie fixtures, and the shops they registered

STORES REMOVED BY NAME, separately from their owners:

  * the three MOCK stores (DNA Jordan, Carrefour Jordan, City Center) carry
    invented prices. They were seeded to demonstrate comparison before real
    stores were scraped, and on a public URL an invented price sitting next
    to a real one is the one thing a price comparison site must never do.

  * the merchant demo shops. Every merchant store on this platform today is a
    test: there is no real shop signed up yet.

Deleting a store cascades to its listings, prices and price history, which
leaves PRODUCTS with no listings at all -- rows nothing can ever price. Those
are removed last, and only when nothing references them.

Run with --apply to actually delete. Without it, this only reports.

    cd backend
    .venv/Scripts/python.exe scripts/cleanup_test_data.py            # dry run
    .venv/Scripts/python.exe scripts/cleanup_test_data.py --apply    # delete
"""

import sys

sys.path.insert(0, ".")

from sqlalchemy import text  # noqa: E402

from app.database import SessionLocal  # noqa: E402

# The only accounts that survive. Everything else is a test artefact.
KEEP_USERS = (
    "salem-demo@example.com",   # the admin; deleting it locks everyone out
    "salemasad476@gmail.com",
    "salemss@gmail.com",
    "salem@gmail.com",
)

# Stores removed regardless of who owns them.
DROP_STORES = (
    # Mock: invented prices, seeded before real scraping existed.
    "DNA Jordan",
    "Carrefour Jordan",
    "City Center",
)

# Stores whose prices were never scraped from a real feed. Identified by
# having no owner-supplied product URL on any listing -- a scraped listing
# always carries the store's own product page, and a hand-entered one cannot.
DROP_MERCHANT_STORES = True


def main() -> int:
    apply = "--apply" in sys.argv
    db = SessionLocal()
    try:
        users = db.execute(
            text("select id, email, role from users order by id")
        ).fetchall()
        doomed_users = [u for u in users if u[1] not in KEEP_USERS]
        kept_users = [u for u in users if u[1] in KEEP_USERS]

        if not any(u[2] == "admin" for u in kept_users):
            print("REFUSING: no admin account would survive. Check KEEP_USERS.")
            return 1

        stores = db.execute(
            text(
                "select s.id, s.name, s.owner_user_id, "
                "(select count(*) from product_aliases a where a.store_id = s.id) "
                "from stores s order by s.id"
            )
        ).fetchall()

        doomed_stores = [
            s for s in stores
            if s[1] in DROP_STORES
            or (DROP_MERCHANT_STORES and s[2] is not None)
        ]
        kept_stores = [s for s in stores if s not in doomed_stores]

        print(f"users   : {len(users):>4}  keep {len(kept_users):>3}  "
              f"delete {len(doomed_users):>3}")
        print(f"stores  : {len(stores):>4}  keep {len(kept_stores):>3}  "
              f"delete {len(doomed_stores):>3}")

        print("\nKEEPING these accounts:")
        for uid, email, role in kept_users:
            print(f"    #{uid:<4} {email:<32} {role}")

        print("\nKEEPING these stores:")
        for sid, name, owner, listings in kept_stores:
            print(f"    #{sid:<4} {name:<30} {listings} listings")

        print("\nDELETING these stores:")
        for sid, name, owner, listings in doomed_stores:
            why = "mock prices" if name in DROP_STORES else "merchant test shop"
            print(f"    #{sid:<4} {name:<30} {listings:>3} listings  ({why})")

        if not apply:
            print(f"\nDRY RUN -- would delete {len(doomed_users)} users and "
                  f"{len(doomed_stores)} stores, then any product left with no "
                  "listings. Pass --apply to do it.")
            return 0

        store_ids = [s[0] for s in doomed_stores]
        user_ids = [u[0] for u in doomed_users]

        # Stores first, explicitly: some belong to accounts that survive (the
        # admin registered one while testing), so the user cascade alone would
        # miss them.
        if store_ids:
            db.execute(
                text("delete from stores where id = any(:ids)"), {"ids": store_ids}
            )
        if user_ids:
            db.execute(
                text("delete from users where id = any(:ids)"), {"ids": user_ids}
            )
        db.commit()

        # Products stranded by the store deletions. Checked against user data
        # first: a wishlist or alert pointing at one is a reason to stop, not
        # a row to quietly remove.
        stranded = db.execute(
            text(
                "select p.id from products p "
                "where not exists (select 1 from product_aliases a "
                "                  where a.product_id = p.id)"
            )
        ).fetchall()
        stranded_ids = [row[0] for row in stranded]

        if stranded_ids:
            referenced = db.execute(
                text(
                    "select count(*) from ("
                    "  select product_id from wishlist_items "
                    "  union all select product_id from price_alerts) t "
                    "where product_id = any(:ids)"
                ),
                {"ids": stranded_ids},
            ).scalar()
            if referenced:
                print(f"\nNOTE: {referenced} wishlist/alert row(s) point at "
                      "stranded products; they cascade with the product.")
            db.execute(
                text("delete from products where id = any(:ids)"),
                {"ids": stranded_ids},
            )
            db.commit()

        print(f"\nDeleted {len(user_ids)} users, {len(store_ids)} stores, "
              f"{len(stranded_ids)} stranded products.")
        for label, query in (
            ("users", "select count(*) from users"),
            ("stores", "select count(*) from stores"),
            ("products", "select count(*) from products"),
            ("listings", "select count(*) from product_aliases"),
            ("prices", "select count(*) from prices"),
        ):
            print(f"    {label:<10} {db.execute(text(query)).scalar()}")
        return 0
    finally:
        db.close()


if __name__ == "__main__":
    raise SystemExit(main())
