"""merchant listing photos

Revision ID: ee543f078cff
Revises: c5a71d3e9f04
Create Date: 2026-09-01 23:48:21.931811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee543f078cff'
down_revision: Union[str, None] = 'c5a71d3e9f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alias_id'], ['product_aliases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_photos_alias_id'), 'listing_photos', ['alias_id'], unique=True)
    op.create_index(op.f('ix_listing_photos_checksum'), 'listing_photos', ['checksum'], unique=False)
    op.create_index(op.f('ix_listing_photos_id'), 'listing_photos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_photos_id'), table_name='listing_photos')
    op.drop_index(op.f('ix_listing_photos_checksum'), table_name='listing_photos')
    op.drop_index(op.f('ix_listing_photos_alias_id'), table_name='listing_photos')
    op.drop_table('listing_photos')
    # ### end Alembic commands ###
