"""store money as numeric not float

JOD is a three-decimal currency and the scraped feeds return values like
"136.000". Binary floating point cannot represent most decimal fractions
exactly, and these columns are summed (price + delivery) and then COMPARED --
to pick the cheapest store, and to decide whether a price alert has been met.
Two stores a thousandth of a dinar apart could be ordered wrongly, and an alert
could sit unmet at exactly its target.

Postgres casts double precision to numeric implicitly, so no USING clause is
needed. Existing values are rounded to 3 decimals, which for prices that were
only ever written with 2-3 decimals is the value that was meant all along.


Revision ID: a0bb26518347
Revises: ec6bbb0c6be4
Create Date: 2026-08-24 05:06:01.263103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0bb26518347'
down_revision: Union[str, None] = 'ec6bbb0c6be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_alerts', 'target_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('price_history', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('prices', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('prices', 'delivery_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'delivery_cost',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('prices', 'price',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('price_history', 'price',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('price_alerts', 'target_price',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
